:imagesdir: ../assets/images
== Module 1: Workshop Setup and Environment Walkthrough

This module focuses on the platform setup. 


== Workshop Setup

. To provision the demo you will perform the following steps - each of which are explained in detail in the next sections:
.. Gain access to Red Hat OpenShift. This demo has been tested on OpenShift 4.18
. Ensure you have the tools `oc` and `ansible` installed in your local environment such as your laptop
. Access the OpenShift cluster with cluster-admin privileges
. Log in to OpenShift with cluster-admin role via cli. 
. Run the Ansible playbook
. Run a bunch of scripts to deploy the Solution Pattern in your OpenShift cluster

== Before getting started

Here is the list of tools you need in your local enviroment so that you can use the automated installation.

. OpenShift Client https://docs.openshift.com/container-platform/4.18/cli_reference/openshift_cli/getting-started-cli.html[oc^]
. https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible CLI^]
. https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html[Ansible kubernetes.core module^]

. To check if you have the cli tools, you can open your terminal and use following commands:
```sh
oc version #openshift cli client
ansible --version
ansible-galaxy --version
ansible-galaxy collection list #the list should include kubernetes.core
```

. If you do not see *kubernetes.core* collection listed, you can install it with `ansible-galaxy`:
```
ansible-galaxy collection install kubernetes.core
```

== Git clone the Ansible playbook 

. Login to your OpenShift cluster as cluster-admin (because a number of operators will need to be installed)

. Click on the username on the top right hand, and then click on Copy login command. This will open another tab and you will need to login again. Click on Display token link, and copy the command under Log in with this token. This will look like this

. Or you can login using the `oc` cli tool
+
```
oc login <your-openshift-api-url> -u <username> -p <password>
```
. Clone the ansible scripts as follows in an appropriate folder in your local environment

```
git clone https://github.com/learn-quarkus/ibm-globex-ai-ansible
```


== Setup LLM API Keys
. Open the ansible scripts folder you just cloned in your local IDE
. Make a copy of the *inventories/inventory.template* file and name it *inventory*
. Update the following variables with your LLM API keys
+
NOTE: This is an example of OpenAI modelnames that this demo has been tested with. You can use other LLM providers as well by updating the model names and base urls accordingly.
```
# moderation
moderation_llm_api_key=<api-key>
moderation_llm_model_name=omni-moderation-latest
moderation_llm_base_url=https://api.openai.com/v1

# emailwriter
emailwriter_llm_api_key=<api-key>
emailwriter_llm_model_name=gpt-4o-mini
emailwriter_llm_base_url=https://api.openai.com/v1

# sentiment
sentiment_llm_api_key=<api-key>
sentiment_llm_model_name=gpt-4o-mini
sentiment_llm_base_url=https://api.openai.com/v1

# summary
summary_llm_api_key=<api-key>
summary_llm_model_name=gpt-4o-mini
summary_llm_base_url=https://api.openai.com/v1
```



== Install the demo


. Navigate to the *ansible* folder
. Run the ansible playbook as shown below. This will take a few minutes to complete. Ensure that the ansible playbook is deployed without errors
+
```
ansible-playbook playbooks/ocp4_workload_globex_ai_poc.yml -e ACTION=create -i inventories/inventory
```
. This is the output you get from the above ansible command:
+
```
PLAY RECAP 
**********************************************
localhost : ok=67 changed=3 unreachable=0 failed=0 skipped=33 rescued=0 ignored=0
```

That's it! You are set to try out this demo! ｡◕‿◕｡
